/**
 * Copyright 2012 Andrew Bythell, abythell@ieee.org
 *
 * This file is part of libgphoto2-jna.
 *
 * libgphoto2-jna is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * libgphoto2-jna is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * libphoto2-jna. If not, see <http://www.gnu.org/licenses/>.
 */
package com.angryelectron.libgphoto2;
import java.util.Arrays;
import java.util.List;

import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemDeleteAllFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemDeleteFileFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemDirFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemGetFileFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemGetInfoFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemListFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemPutFileFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemSetInfoFunc;
import com.angryelectron.libgphoto2.Gphoto2Library.CameraFilesystemStorageInfoFunc;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/gphoto2/gphoto2-filesys.h:1060</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraFilesystemFuncs extends Structure {
	/// C type : CameraFilesystemListFunc
	public CameraFilesystemListFunc file_list_func;
	/// C type : CameraFilesystemListFunc
	public CameraFilesystemListFunc folder_list_func;
	/// C type : CameraFilesystemPutFileFunc
	public CameraFilesystemPutFileFunc put_file_func;
	/// C type : CameraFilesystemDeleteAllFunc
	public CameraFilesystemDeleteAllFunc delete_all_func;
	/// C type : CameraFilesystemGetInfoFunc
	public CameraFilesystemGetInfoFunc get_info_func;
	/// C type : CameraFilesystemSetInfoFunc
	public CameraFilesystemSetInfoFunc set_info_func;
	/// C type : CameraFilesystemDirFunc
	public CameraFilesystemDirFunc make_dir_func;
	/// C type : CameraFilesystemDirFunc
	public CameraFilesystemDirFunc remove_dir_func;
	/// C type : CameraFilesystemGetFileFunc
	public CameraFilesystemGetFileFunc get_file_func;
	/// C type : CameraFilesystemDeleteFileFunc
	public CameraFilesystemDeleteFileFunc del_file_func;
	/// C type : CameraFilesystemStorageInfoFunc
	public CameraFilesystemStorageInfoFunc storage_info_func;
	/**
	 * for later use. Remove one if you add a new function<br>
	 * C type : void*[31]
	 */
	public Pointer[] unused = new Pointer[31];
	public CameraFilesystemFuncs() {
		super();
	}
	@SuppressWarnings("rawtypes")
  @Override
  protected List getFieldOrder() {
	  return Arrays.asList(new String[]{"file_list_func", "folder_list_func", "put_file_func", "delete_all_func", "get_info_func", "set_info_func", "make_dir_func", "remove_dir_func", "get_file_func", "del_file_func", "storage_info_func", "unused"});
  };

	public static class ByReference extends CameraFilesystemFuncs implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraFilesystemFuncs implements Structure.ByValue {
		
	};
}
