package com.angryelectron.libgphoto2;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/gphoto2/gphoto2-filesys.h:901</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraFileInfo extends Structure {
	/// C type : CameraFileInfoPreview
	public CameraFileInfoPreview preview;
	/// C type : CameraFileInfoFile
	public CameraFileInfoFile file;
	/// C type : CameraFileInfoAudio
	public CameraFileInfoAudio audio;
	public CameraFileInfo() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"preview", "file", "audio"});
	}
	/**
	 * @param preview C type : CameraFileInfoPreview<br>
	 * @param file C type : CameraFileInfoFile<br>
	 * @param audio C type : CameraFileInfoAudio
	 */
	public CameraFileInfo(CameraFileInfoPreview preview, CameraFileInfoFile file, CameraFileInfoAudio audio) {
		super();
		this.preview = preview;
		this.file = file;
		this.audio = audio;
		initFieldOrder();
	}
	public static class ByReference extends CameraFileInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraFileInfo implements Structure.ByValue {
		
	};
}
