package com.angryelectron.libgphoto2;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/gphoto2/gphoto2-port-info-list.h:29</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class GPPortInfo extends Structure {
	/**
	 * @see GPPortType<br>
	 * < \brief The type of this port.<br>
	 * C type : GPPortType
	 */
	public int type;
	/**
	 * < \brief The name of this port (usb:)<br>
	 * C type : char[64]
	 */
	public byte[] name = new byte[64];
	/**
	 * < \brief The path of this port (whatever is after the :)<br>
	 * C type : char[64]
	 */
	public byte[] path = new byte[64];
	/**
	 * Private<br>
	 * < \brief Internal pathname of the port driver. Do not use outside of the port library.<br>
	 * C type : char[1024]
	 */
	public byte[] library_filename = new byte[1024];
	public GPPortInfo() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"type", "name", "path", "library_filename"});
	}
	/**
	 * @param type @see GPPortType<br>
	 * < \brief The type of this port.<br>
	 * C type : GPPortType<br>
	 * @param name < \brief The name of this port (usb:)<br>
	 * C type : char[64]<br>
	 * @param path < \brief The path of this port (whatever is after the :)<br>
	 * C type : char[64]<br>
	 * @param library_filename Private<br>
	 * < \brief Internal pathname of the port driver. Do not use outside of the port library.<br>
	 * C type : char[1024]
	 */
	public GPPortInfo(int type, byte name[], byte path[], byte library_filename[]) {
		super();
		this.type = type;
		if (name.length != this.name.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.name = name;
		if (path.length != this.path.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.path = path;
		if (library_filename.length != this.library_filename.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.library_filename = library_filename;
		initFieldOrder();
	}
	public static class ByReference extends GPPortInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends GPPortInfo implements Structure.ByValue {
		
	};
}
