package com.angryelectron.libgphoto2;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/gphoto2/gphoto2-port.h:93</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class GPPortSettingsDisk extends Structure {
	/**
	 * < \brief Path in the UNIX fs which corresponds to gphoto2 /<br>
	 * C type : char[128]
	 */
	public byte[] mountpoint = new byte[128];
	public GPPortSettingsDisk() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"mountpoint"});
	}
	/**
	 * @param mountpoint < \brief Path in the UNIX fs which corresponds to gphoto2 /<br>
	 * C type : char[128]
	 */
	public GPPortSettingsDisk(byte mountpoint[]) {
		super();
		if (mountpoint.length != this.mountpoint.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.mountpoint = mountpoint;
		initFieldOrder();
	}
	public static class ByReference extends GPPortSettingsDisk implements Structure.ByReference {
		
	};
	public static class ByValue extends GPPortSettingsDisk implements Structure.ByValue {
		
	};
}
